# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WorldCountries API - Deploy to Heroku

on:
  # push:
    # branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        echo "Git user set successfully"
    - name: Setup netrc credentials for Heroku CLI
      uses: little-core-labs/netrc-creds@v2.0.0
      with:
        creds: |
          [
            {
              "machine": "api.heroku.com",
              "login": "${{ secrets.HEROKU_EMAIL }}",
              "password": "${{ secrets.HEROKU_API_KEY }}"
            },
            {
              "machine": "git.heroku.com",
              "login": "${{ secrets.HEROKU_EMAIL }}",
              "password": "${{ secrets.HEROKU_API_KEY }}"
            }
          ]
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Set up Heroku CLI for Ubuntu
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        heroku auth:login
        heroku plugins:install java
    - name: WorldCountries API - Build and deploy to Heroku
      run: |
        cd worldcountries-api
        echo "Working directory: worldcountries-api"
        mvn –q clean package
        heroku deploy:jar target/worldcountries.jar --jdk 8 --app worldcountries-api