# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: WorldCountries Admin - Build with Maven
      run: 
        mvn -B clean package --file worldcountries-admin/pom.xml
        HEROKU_API_KEY=${{ secrets.HEROKU_AUTH_TOKEN }} mvn -B heroku:deploy-only --file worldcountries-admin/pom.xml
    # - name: WorldCountries API - Build with Maven