# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI/CD with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        echo "Git user set successfully"
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Set up Heroku CLI for Ubuntu
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        heroku plugins:install java
        heroku auth:login -u ${{ secrets.HEROKU_AUTH_USER }} -p ${{ secrets.HEROKU_AUTH_TOKEN }}
    - name: Change working directory to worldcountries-admin
      run: cd worldcountries-admin && ls -ltr
    - name: WorldCountries Admin - Build with Maven
      run: mvn clean package
    - name: WorldCountries Admin - Deploy to Heroku
      run: heroku deploy:jar target/worldcountries-admin.jar --jdk 8 --app worldcountries-admin
    - name: Change working directory to worldcountries-api
      run: cd worldcountries-api && ls -ltr
    - name: WorldCountries API - Build with Maven
      run: mvn clean package
    - name: WorldCountries API - Deploy to Heroku
      run: heroku deploy:jar target/worldcountries.jar --jdk 8 --app worldcountries-api